//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicefMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionEvent
    {
        public int RegionEventId { get; set; }
        public int RegionId { get; set; }
        public string EventHeadline { get; set; }
        public string EventDescription { get; set; }
        public int Severity { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
